### ISSUE TITLE
Dark- /Lightmode

### ISSUE THREAD

**Issue by aero23h** [TU-DARMSTADT-BP-2025-64/ptw-evaluation-assist#13]
| Beschreibung | Akzeptanzkriterium |
|-----------------| ----------------------|
| Button welcher den Dastellungsmodus wechselt. | Über den Button oben rechts kann der Darstellungsmodus angepasst werden und zwischen light- und darkmode gewechselt werden. |

| Geschätzter Aufwand (Story Points) | Umgesetzt in Iteration | Tatsächlicher Aufwand (Std.) | Velocity (Std./Story Point) |
|------------------------------------|------------------|-------------------------|------------------------------|
| 2 | 3 | 5 | 2,5 |

|Bemerkungen |
|----------------|
| ... |

**Comment by JacobDeuchert** [comment]
Wurde implementiert, für die Stylefixes wird dann später ein anderes Ticket eröffnet
